# -*- coding: utf-8 -*-
"""API Home com flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wBcEDE7CEd1pIBFj9JaXx3-Q2O5-ZRNm
"""

!pip install flask
!pip install flask-ngrok
!pip install fastapi nest-asyncio pyngrok uvicorn

import pandas as pd
import json

info = [{
        'numero': 1,
        'nome': 'Alex',
        'idade' : '25',
        'cidade': 'Toronto',
        'pais': 'Canada',
},
       {
        'numero': 2,
        'nome': 'David',
        'idade' : '26',
        'cidade': 'San Francisco',
        'pais': 'USA',
       },
        {
        'numero': 3,
        'nome': 'Mateus',
        'idade' : '27',
        'cidade': 'Paris',
        'pais': 'Franca',
        },
        {
        'numero': 4,
        'nome': 'Marcos',
        'idade' : '28',
        'cidade': 'Londres',
        'pais': 'UK',
},
       {
        'numero': 5,
        'nome': 'Matias',
        'idade' : '29',
        'cidade': 'Bangalore',
        'pais': 'India',
}]


with open('dados.json', 'w') as arquivo:
    arquivo.write(json.dumps(info))

with open('dados.json', 'r') as arquivo:
    texto = arquivo.read()
    dados = json.loads(texto)

with open('dados.json', 'r') as arquivo:
    texto = arquivo.read()
    dados = json.loads(texto)
print(dados['nome'])

from fastapi import FastAPI
import nest_asyncio
from pyngrok import ngrok
import uvicorn

app = FastAPI()

@app.get('/index')
async def index():
  return (info)

ngrok_tunnel = ngrok.connect(8000)
print('Public URL:', ngrok_tunnel.public_url)
nest_asyncio.apply()
uvicorn.run(app, port=8000)
